on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ fromJSON('{"macos-latest":"blacksmith-6vcpu-macos-latest","ubuntu-latest":"blacksmith-2vcpu-ubuntu-2404","windows-latest":"blacksmith-2vcpu-windows-2025"}')[matrix.os] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23.x"
      - run: yarn install --frozen-lockfile
      - run: yarn test-compile
      - run: yarn compile
      - run: yarn lint
        if: runner.os != 'Windows' # eslint on windows complains about CR/LF
      - run: yarn package
      - run: xvfb-run -a yarn test
        if: runner.os == 'Linux'
      - run: yarn test
        if: runner.os == 'macOS'
